name: CI Build and Push Multi-Arch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm/v7,linux/arm64,linux/amd64

      - name: Set up Docker Buildx (docker-container driver)
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          install: true

      - name: Create builder instance (ensure running)
        run: |
          docker buildx inspect multi-builder >/dev/null 2>&1 || docker buildx create --name multi-builder --use
          docker buildx inspect --bootstrap

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          tags: ghcr.io/arkinfotech24/dummy-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify image manifest
        run: |
          echo "Listing manifest for image:"
          docker run --rm mplatform/mquery:latest ghcr.io/arkinfotech24/dummy-app:${{ github.sha }}

