name: CI Build and Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Target environment'
        required: true
        default: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/arkinfotech24/dummy-app:${{ github.sha }}
          platforms: linux/arm/v7,linux/arm64,linux/amd64
